import Head from 'next/head'
import styles from '../styles/Common.module.css'
import Inner from "../components/parts/Inner"
import Button from "../components/parts/LinkButton"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Inner styles="py-24">
          <h1 className="text-center text-5xl font-medium mb-5">
            舞台のセッティングシートを作ろう
          </h1>
          <p className="text-center text-lg mb-12 font-gray text-zinc-500">
            Design Sheetsなら舞台用セッティングシートを誰でも簡単に作成できます
            <br />
            吹奏楽やオーケストラのシート表を作成してみましょう
          </p>
          <Button
            href="/edit"
            text="始める"
            styles="bg-primary text-white hover:bg-hoverPrimary text-center max-w-[161px] mx-auto"
          />
        </Inner>
      </main>
    </div>
  );
}
